Stack cache and acceleration
alan-turing-institute/MLJBase.jl pull request #767
Opened 2022-05-12 16:52 UTC by olivierlabayle

Following up on: https://github.com/JuliaAI/MLJBase.jl/pull/759

This adds two fields to the Stack to enable/disable submachines caching and the network's acceleration:

- `cache`: Whether submachines will be caching data or not.
- `acceleration`: Acceleration mode of the learning network.

2022-05-16 00:25 UTC, ablaom commented on test/Project.toml
> +Parameters = "d96e819e-fc66-5662-9728-84c9c7592b0a"
I think you have forgotten to remove the corresponding entries from the core Project.toml: 
https://github.com/JuliaAI/MLJBase.jl/blob/37a5256fa85eec02d91e340b0f4c0a1ddcbbf44a/Project.toml#L51

2022-05-16 00:28 UTC, ablaom commented on src/composition/models/stacking.jl
> +- `cache`: Weither machines created in the learning network will cache data or not.
```suggestion
- `cache`: Whether machines created in the learning network will cache data or not.
```

2022-05-16 00:34 UTC, ablaom commented on src/composition/models/stacking.jl
> +  mode of the learning network.
Some users will use `Stack` but not be familiar with the term "learning network", so I suggest dropping the reference here. If they try an unsupported resource, they get an informative message explaining that. 

```suggestion
- `acceleration`: an `AbstractResource` defining the mode of parallelization for training the stack
```

2022-05-16 00:37 UTC, ablaom commented on src/composition/models/stacking.jl
> +  mode of the learning network.
But we should also update this line: https://github.com/JuliaAI/MLJBase.jl/blob/37a5256fa85eec02d91e340b0f4c0a1ddcbbf44a/src/composition/learning_networks/nodes.jl#L210

to include `CPUThreads()` as a valid resource.

2022-05-16 00:50 UTC, ablaom commented
@olivierlabayle This is great, thank you. 

Since this adds `CPUThreads` as an option for training *any* learning network node, it's probably prudent to add some more tests for this. I would like to see that the `CPUThreads` analogue of these tests also a pass:

https://github.com/JuliaAI/MLJBase.jl/blob/4d1ed14e7b1034fbe00c4dde3550144180da5225/test/composition/learning_networks/machines.jl#L194

Note that `@test_mach_sequence` already provides a list of multiple acceptable training sequences, to handle case of asynchronous training. So they "should" pass. 

Probably we can just wrap these tests in an `@test_accelerated` block, as we have elsewhere, but exclude ` CPUProcesses`. 

I don't think we need to check both options give same results. You already do this for `Stack`. What do you think?

2022-05-16 00:52 UTC, ablaom requested changes
My comments and test suggestions not withstanding, I'm already happy with this "draft" PR.

2022-05-18 00:31 UTC, olivierlabayle commented on test/Project.toml
> +Parameters = "d96e819e-fc66-5662-9728-84c9c7592b0a"
Exact! 👍

2022-05-18 00:53 UTC, olivierlabayle commented
@ablaom Thank you for this early review. I had indeed only marked this as a draft because I wanted to be a bit more thorough about the testing of the new multithreading feature. 

I will need to have a proper look at the `@test_accelerated` and `@test_mach_sequence` macros that you suggest. If the models in the sequence are completely deterministic I think I should make sure the results are concordent at least to some extent.

2022-05-19 00:14 UTC, olivierlabayle commented
I have incremented the testset you suggested with `CPUThreads()` as a resource for the custom learning network. Unfortunately, I couldn't make use of the `@testset_accelerated` macro with the `exclude` keyword. Besides, what is the advantage over the classic `@testset for accel in accelerations end`? (This is what I have used)

2022-05-19 05:21 UTC, ablaom commented
> Besides, what is the advantage over the classic @testset for accel in accelerations end? (This is what I have used)

👍🏾 Probably that macro was written before that syntax was available?? I didn't know about it myself.

2022-05-19 05:24 UTC, ablaom approved these changes
I'm happy with this, @olivierlabayle

I'm going to recommend that @OkonSamuel also reviews this, as he is more familiar with multithreading issues. He is pretty busy, but I think it's worth getting an expert to look over this.

2022-05-30 04:21 UTC, ablaom commented
Following suggestion of @OkonSamuel I thing we should test multi-threading works for a variety of models. I am working on some enhancements of [MLJTestIntegration.jl](https://github.com/JuliaAI/MLJTestIntegration.jl) to automate such a test, and will check back here when that is ready.

2022-05-30 05:23 UTC, olivierlabayle commented
> Following suggestion of @OkonSamuel we should test multi-threading works for a variety of component models. I am working on some enhancements of [MLJTestIntegration.jl](https://github.com/JuliaAI/MLJTestIntegration.jl) to automate such a test, and will check back here when that is ready.

Great idea, I'll be waiting then!

2022-06-03 01:27 UTC, ablaom commented on src/composition/models/stacking.jl
> +    name === :cache && return getfield(stack, :cache)
You need to add `:acceleration` and `:cache` to the list of `propertynames` in line 214

2022-06-03 08:28 UTC, olivierlabayle commented on src/composition/models/stacking.jl
> +    name === :cache && return getfield(stack, :cache)
done

2022-06-09 01:04 UTC, ablaom commented on src/composition/models/stacking.jl
> +    Stack(;metalearner=nothing, resampling=CV(), name1=model1, cache=true, acceleration=CPU1(), name2=model2, ...)
This doc-string got a little mangled, with the model1 and model2 being separated. As this has grown passed the length of the line, how about we not list all the options here:

```suggestion
    Stack(;metalearner=nothing, name1=model1, name2=model2, keyword_options...)
```

2022-06-09 21:14 UTC, ablaom commented
@olivierlabayle I needed to rebase this and am closing in favour of https://github.com/JuliaAI/MLJBase.jl/pull/785. The rebase includes a fix for the doc string marked above.

2022-06-09 21:14 UTC, closed without merging