closes #784 by fixing typename + tests
alan-turing-institute/MLJBase.jl pull request #786
Opened 2022-06-10 08:43 UTC by tlienart

* fixes `typename` for `DataFrames.DataFrame` object, tested with `1.0` to `1.7` seems ok
* added simple tests for it (required adding `DataFrames` to the `extras`)

2022-06-10 11:39 UTC, OkonSamuel commented on src/interface/data_utils.jl
> +        cols = Tables.columntable(X) # named tuple of vectors
```suggestion
        cols = Tables.columns(X)
```

2022-06-10 11:39 UTC, OkonSamuel commented on src/interface/data_utils.jl
> +        return cols[c]
```suggestion
        return Tables.getcolumn(cols, c)
```

2022-06-10 11:41 UTC, OkonSamuel commented on src/interface/data_utils.jl
> +        cols = Tables.columntable(X) # named tuple of vectors
In this case there is no need to generate a named tuple of vectors which would have bad compile time performance. In fact I say we do not need the `isdataframe` check in this case.

2022-06-10 12:30 UTC, OkonSamuel commented on src/interface/data_utils.jl
>  function MMI.selectcols(::FI, ::Val{:table}, X, c::AbstractArray)
```suggestion
function MMI.selectcols(::FI, ::Val{:table}, X, c::Union{Colon, AbstractArray})
```

2022-06-10 12:58 UTC, tlienart commented
thanks for the review @OkonSamuel feel free to take this over, I'm not close enough to the Tables API to know what's best so I trust your choices are better, it might be good to check the tests are right, maybe do a side test with what brought Jack_N to open the issue in the first place and check that there's no bottleneck anymore?

2022-06-10 13:04 UTC, jackn11 commented
Thank you both for helping with the changes. Also, it may be a good idea to make the slight modification to the selectcols function so that the '!' is not needed in the if statement. The code is below so you can see what I mean. Removing the unnecessary double negative should help keep the code clean and understandable.

`function MMI.selectcols(::FI, ::Val{:table}, X, c::Union{Symbol, Integer})
    if isdataframe(X)
        return X[!, c]
    else
        cols = Tables.columntable(X) # named tuple of vectors
        return cols[c]
    end
end

function MMI.selectcols(::FI, ::Val{:table}, X, c::AbstractArray)
    if isdataframe(X)
        return X[!, c]
    else
        cols = Tables.columntable(X) # named tuple of vectors
        newcols = project(cols, c)
        return Tables.materializer(X)(newcols)
    end
end`

2022-06-10 22:57 UTC, ablaom commented on src/interface/data_utils.jl
> +typename(X) = split(string(supertype(typeof(X))), '.')[end]
```suggestion
# NOTE. THE FOLLOWING USES NON PUBLIC JULIA API. 
# It is a hack to avoid DataFrames as a dependency (see implementation
# of `selectrows`) until https://github.com/JuliaData/Tables.jl/pull/278
# is resolved
typename(X) = split(string(supertype(typeof(X))), '.')[end]
```

2022-06-10 23:00 UTC, ablaom requested changes
@OkonSamuel I'm happy with this, modulo my single suggestion. Please merge and tag a new release at your leisure.

2022-06-11 07:50 UTC, merged

2022-06-11 07:51 UTC, tlienart commented
I just merged (it was my branch so not sure if sam could do it) will leave the tag & release to you guys

2022-06-12 21:28 UTC, ablaom commented
Thank you @tlienart and @OkonSamuel . A new release just tagged.