Fixes to `evaluate` standard error calculation to fix display issue
alan-turing-institute/MLJBase.jl pull request #872
Opened 2022-12-05 03:02 UTC by ablaom

Closes #871.

2022-12-05 09:17 UTC, rikhuijzer commented on test/resampling.jl
> +    show(io, MIME("text/plain"))
```suggestion
    confusion_table = sprint(show, "text/plain", evaluations.measurement[1])
    @test contains(confusion_table, "Ground Truth")
```
I've also tried to test for "N/A" being contained in `display(evaluations)`, but was unable for some reason:
```julia
julia> display(evaluations)
PerformanceEvaluation object with these fields:
  measure, operation, measurement, per_fold,
  per_observation, fitted_params_per_fold,
  report_per_fold, train_test_rows
Extract:
┌───────────────────┬──────────────┬───────────────────────────────────────────
│ measure           │ operation    │ measurement                              ⋯
├───────────────────┼──────────────┼───────────────────────────────────────────
│ ConfusionMatrix(  │ predict_mode │ ConfusionMatrixObject{2}([20 30; 30 20], ⋯
│   perm = nothing) │              │                                          ⋯
└───────────────────┴──────────────┴───────────────────────────────────────────
                                                              3 columns omitted

julia> sprint(show, "text/plain", evaluations)
"PerformanceEvaluation object with these fields:\n  measure, operation, measurement, per_fold,\n  per_observation, fitted_params_per_fold,\n  report_per_fold, train_test_rows\nExtract:\n┌───────────────────┬──────────────┬───────────────────────────────────────────────────" ⋯ 4277 bytes ⋯ "────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘\n"
```
For some reason, the `PrettyTables.jl` output appears to be truncated. Do you maybe know how to circumvent this? This is optional of course. The PR looks good to me
```

2022-12-05 20:33 UTC, ablaom commented on test/resampling.jl
> +    show(io, MIME("text/plain"))
Your suggestion is really an *additional* test. It won't catch the original fail, which only happens if you try to display the full PerformanceEvaluation object, right? 

I don't know how to handle the truncation. Was hoping https://github.com/ronisbr/PrettyTables.jl/issues/87 would happen, but that's been a while. Happy for suggestions, but we should merge this to address the bug.

2022-12-06 09:14 UTC, rikhuijzer approved these changes

2022-12-06 09:43 UTC, rikhuijzer requested changes
Let's make the test
```julia

2022-12-06 09:43 UTC, rikhuijzer commented on test/resampling.jl
> +    @test contains(confusion_table, "Ground Truth")
```suggestion
    printed_evaluations = sprint(show, "text/plain", evaluations)
    @test contains(printed_evaluations, "N/A")
```

This catches the failure reported in #871. My `sprint(show, "text/plain", evaluations.measurement[1])` test didn't so can be removed.

2022-12-06 09:47 UTC, rikhuijzer commented on test/resampling.jl
> +    @test contains(confusion_table, "Ground Truth")
With old code in `src/resampling` (without this PR):
```julia
julia> sprint(show, "text/plain", evaluations)
ERROR: MethodError: no method matching /(::MLJBase.ConfusionMatrixObject{2}, ::Int64)
[...]
```
With new code in `src/resampling` (with this PR):
```julia
julia> sprint(show, "text/plain", evaluations) |> print
PerformanceEvaluation object with these fields:
  measure, operation, measurement, per_fold,
  per_observation, fitted_params_per_fold,
  report_per_fold, train_test_rows
Extract:
┌───────────────────┬──────────────┬──────────────────────────────────────────────────────┬─────────┬────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│ measure           │ operation    │ measurement                                          │ 1.96*SE │ per_fold                                                                                                                                                                                                                                                                                                                                           │
├───────────────────┼──────────────┼──────────────────────────────────────────────────────┼─────────┼────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┤
│ ConfusionMatrix(  │ predict_mode │ ConfusionMatrixObject{2}([18 32; 32 18], ["0", "1"]) │ N/A     │ MLJBase.ConfusionMatrixObject{2}[ConfusionMatrixObject{2}([6 11; 0 0], ["0", "1"]), ConfusionMatrixObject{2}([0 0; 10 7], ["0", "1"]), ConfusionMatrixObject{2}([7 10; 0 0], ["0", "1"]), ConfusionMatrixObject{2}([0 0; 10 7], ["0", "1"]), ConfusionMatrixObject{2}([5 11; 0 0], ["0", "1"]), ConfusionMatrixObject{2}([0 0; 12 4], ["0", "1"])] │
│   perm = nothing) │              │                                                      │         │                                                                                                                                                                                                                                                                                                                                                    │
└───────────────────┴──────────────┴──────────────────────────────────────────────────────┴─────────┴────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
```

2022-12-06 21:17 UTC, ablaom commented on test/resampling.jl
> +    @test contains(confusion_table, "Ground Truth")
I stand corrected. Thanks for the review and taking the time to sort out my misunderstanding.

2022-12-06 22:02 UTC, merged

2022-12-06 22:02 UTC, ablaom commented
@rikhuijzer Thank you for reviewing and improving this PR.

2022-12-07 08:54 UTC, rikhuijzer commented
> @rikhuijzer Thank you for reviewing and improving this PR.

Thank you for your work on MLJ :heart: